### PR TITLE
Display ENS on /scan route

### PR DESCRIPTION
**Pull request by lndgalante**
## What's new?
- Displays ENS instead of account address.

## Closes issue(s)
- [POAP-9](https://xivis.atlassian.net/secure/RapidBoard.jspa?rapidView=120&projectKey=POAP&modal=detail&selectedIssue=POAP-9)
- [POAP-10](https://xivis.atlassian.net/secure/RapidBoard.jspa?rapidView=120&projectKey=POAP&modal=detail&selectedIssue=POAP-10)

## Changes include
- [x] Display ENS instead of address, if available, on `/scan/:account`
- [x] Adds `/actions/ens_lookup/:address` endpoint to find the ENS of a particular address
- [x] Adds `dev` script to run Ganache, wait 3s, deploy contracts, run client & server
- [x] Bump dependencies
- [x] Move all `@types` to devDependencies

Note: the product view has this information

## Self-QA Checklist
- [x] I have tested this code
- [x] I have updated the README (if needed)
- [x] This branch has been rebased from dev before creating the pull-request
- [ ] **Pull-request build** has passed

### CODE REVIEW

**Comment by ragonzal** [comment]
@lndgalante please change this PR to the branch `ENS/main` please

**Comment by lndgalante** [comment]
@ragonzal base changed!

**Review by ragonzal — APPROVED** [review]
Good work!

**Comment by lndgalante** [comment]
Thanks!

**Pull request merged**
