### PR TITLE
Burn feature in Backoffice

### PR DESCRIPTION
**Pull request by lndgalante**
## What's new?
- Now the admin could burn a token having it's id beforehand.

## Closes issue(s)
- [POAP-20](https://xivis.atlassian.net/secure/RapidBoard.jspa?rapidView=120&projectKey=POAP&modal=detail&selectedIssue=POAP-20)

## Changes include
- [x] Adds `/admin/burn` and `/admin/burn/:tokenId` routes
- [x] Adds `burnToken` method in `api.ts` file
- [x] Fix layout problems since we target #root 
- [x] Display token information and a `Burn token` action
- [x] Move all yup validation schemas to `/lib/schemas` folder

## Self-QA Checklist
- [x] I have tested this code
- [ ] I have updated the README (if needed)
- [x] This branch has been rebased from dev before creating the pull-request
- [ ] **Pull-request build** has passed

### CODE REVIEW

**Comment by lndgalante** [comment]
@ragonzal I also rebased `/BURN/main` so it's up to date.

**Comment by ragonzal** [comment]
Everything worked as expected on the happy paths, but please let's review the following issues.

#### Token not found
When the admin searches for a token that was not minted yet, we get this error page that is great.
But please let's add a "go back" button so that the user can do something.
Screen Shot 2019-08-01 at 12 07 23 AM

#### Token information
Please, below the description let's add the owner address. Also, we could check for an existing ENS (using the endpoints that we already have `ens_lookup`) to add it in case we find it.
Just one line below the event description: 
`Owner: 0xC55E5DADfA858cA2048D5bB0b536F84913cF4f19` or
`Owner: matoken.eth (0x5A384227B65FA093DEC03Ec34e111Db80A040615)`
Screen Shot 2019-08-01 at 12 08 14 AM

#### API call
When trying to burn, I got this error from the API
Screen Shot 2019-08-01 at 12 11 09 AM

If I removed the `Content-Type` header, it worked correctly. Did it happen to you? Do you know why did I get this error?
Screen Shot 2019-08-01 at 12 11 18 AM

**Comment by lndgalante** [comment]
Thanks for the feedback @ragonzal! Let me know what you think:

- [x] Adds button "Find another token" to go to `/admin/burn`

find-error

- [x] Display token owner and ENS if available
Captura de Pantalla 2019-08-01 a la(s) 10 07 27

- [x] `FST_ERR_CTP_EMPTY_JSON_BODY` it's a Fastify error telling us that we cannot make a Request without a body if we use `'Content-Type': 'application/json'` header so I removed since we're not sending anything in it.

What was not have been tested was the ENS since lives locally but no on the API, but locally doesn't have access to the tokens. And the BURN token functionality since not sure what tokens can be removed or if we can add a test user.

**Review by ragonzal — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
